# Generated by Django 5.0.6 on 2024-10-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicmath', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaFibonacci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(help_text='Número de términos de la secuencia de Fibonacci')),
                ('secuencia', models.JSONField(blank=True, help_text='Secuencia de Fibonacci generada', null=True)),
            ],
        ),
    ]
