# Generated by Django 5.0.6 on 2024-09-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaidaLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravedad', models.FloatField(help_text='Gravedad (m/s^2)')),
                ('coef_resistencia', models.FloatField(help_text='Coeficiente de resistencia del aire')),
                ('altura_inicial', models.FloatField(help_text='Altura inicial (m)')),
                ('intervalo_tiempo', models.FloatField(help_text='Intervalo de tiempo (s)')),
                ('tiempo_total', models.FloatField(blank=True, null=True)),
                ('velocidad_final', models.FloatField(blank=True, null=True)),
                ('altura_final', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
