# Generated by Django 5.0.6 on 2024-09-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnfriamientoNewton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_inicial', models.FloatField(help_text='Temperatura inicial del objeto (°C)')),
                ('temperatura_ambiente', models.FloatField(help_text='Temperatura ambiente (°C)')),
                ('k_enfriamiento', models.FloatField(help_text='Constante de enfriamiento k')),
                ('inter_tiempo', models.FloatField(help_text='Intervalo de tiempo dt (s)')),
            ],
        ),
    ]
