# Generated by Django 5.0.6 on 2024-10-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0002_enfriamientonewton'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitoRC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R', models.FloatField(help_text='Resistencia (ohmios)')),
                ('C', models.FloatField(help_text='Capacitancia (faradios)')),
                ('V_0', models.FloatField(help_text='Voltaje de la fuente (voltios)')),
                ('t_final', models.FloatField(help_text='Tiempo final (segundos)')),
                ('dt', models.FloatField(help_text='Intervalo de tiempo (segundos)')),
            ],
        ),
    ]
